services:
  jekyll:
    image: jekyll-lanyon:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "4000:4000"
      - "35729:35729"  # LiveReload port
    environment:
      - JEKYLL_ENV=development
    entrypoint: ["bundle", "exec", "jekyll", "serve", "--config", "_config.yml,_config_dev.yml", "--host", "0.0.0.0", "--livereload", "--force_polling"]

volumes:
  bundle_cache: